import request from "supertest"
import { jest } from "@jest/globals"
import app from "../../app.js"

beforeEach(() => {
  // This comes from tokens.js in the app.js import.  This apps tries to read env.ACCESS_TOKEN to refresh expired tokens.
  // We don't care whether or not the token is expired here, so let's just state we don't care about tokens in tests.
  updateExpiredToken = jest.fn(() => true)
  isTokenExpired = jest.fn(() => false)
})

afterEach(() => {
  /**
   * Food for thought: delete data generated by tests?  
   * Make a test.store available that uses the same annotationStoreTesting as RERUM tests?
   */
})

describe("Make sure TinyNode demo interface is present.  __core", () => {
  it("/index.html", async () => {
    const response = await request(app)
      .get("/index.html")
      .then(resp => resp)
      .catch(err => err)
    expect(response.statusCode).toBe(200)
    expect(response.header["content-type"]).toMatch(/html/)
  })
})
