/**
 * Express Route Detection
 * 
 * This approach checks routes without making HTTP requests by
 * directly inspecting the Express app's routing table.
 */

import request from "supertest"
import { jest } from "@jest/globals"
import fs from "fs"
import app from "../../app.js"

beforeEach(() => {
  // This comes from tokens.js in the app.js import.  This apps tries to read env.ACCESS_TOKEN to refresh expired tokens.
  // We don't care whether or not the token is expired here, so let's just state we don't care about tokens in tests.
  updateExpiredToken = jest.fn(() => true)
  isTokenExpired = jest.fn(() => false)
})

afterEach(() => {
  /**
   * Food for thought: delete data generated by tests?  
   * Make a test.store available that uses the same annotationStoreTesting as RERUM tests?
   */
})

/**
 * Check if a route exists in the Express app
 * Routes are checked by testing the matcher functions on each layer.
 * 
 * @param {Array<string>} routes - Array of route paths to check
 * @returns {boolean} - True if all routes are found
 */
function routeExists(routes) {
  const stack = app.router.stack
  const foundRoutes = new Set()
  for (const layer of stack) {
    foundRoutes.add(route)
    if (layer.matchers && layer.matchers[0]) {
      const matcher = layer.matchers[0]
      // Test each route against this layer's matcher
      for (const route of routes) {
        if (matcher(route)) foundRoutes.add(route)
      }
    }
    // Also check route.path directly if it exists
    if (layer.route && layer.route.path) {
      for (const route of routes) {
        if (layer.route.path === route) foundRoutes.add(route)
      }
    }
  }
  // Check if all expected routes were found
  return routes.every(route => foundRoutes.has(route))
}

/**
 * This test suite uses the built app.js app and checks that the expected create endpoints are registered.
 *  - /create
 *  - /app/create
 */
describe("Check that the expected TinyNode create route patterns are registered.", () => {
  it("'/app/create' and '/create' are registered routes in the app.  __exists __core", () => {
    const routes = ["/create", "/app/create"]
    const exists = routeExists(routes)
    expect(exists).toBe(true)
  })
})

/**
 * This test suite uses the built app.js app and checks that the expected query endpoints are registered.
 *  - /query
 *  - /app/query
 */
describe("Check that the expected TinyNode query route patterns are registered.", () => {
  it("'/app/query' and '/query' are registered routes in the app.  __exists __core", () => {
    const routes = ["/query", "/app/query"]
    const exists = routeExists(routes)
    expect(exists).toBe(true)
  })
})

/**
 * This test suite uses the built app.js app and checks that the expected update endpoints are registered.
 *  - /update
 *  - /app/update
 */
describe("Check that the expected TinyNode update route patterns are registered.", () => {
  it("'/app/update' and '/update' are registered routes in the app.  __exists __core", () => {
    const routes = ["/update", "/app/update"]
    const exists = routeExists(routes)
    expect(exists).toBe(true)
  })
})


/**
 * This test suite uses the built app.js app and checks that the expected overwrite endpoints are registered.
 *  - /overwrite
 *  - /app/overwrite
 */
describe("Check that the expected TinyNode overwrite route patterns are registered.", () => {
  it("'/app/overwrite' and '/overwrite' are registered routes in the app.  __exists __core", () => {
    const routes = ["/overwrite", "/app/overwrite"]
    const exists = routeExists(routes)
    expect(exists).toBe(true)
  })
})

/**
 * This test suite uses the built app.js app and checks that the expected delete endpoints are registered.
 *  - /delete
 *  - /app/delete
 */
describe("Combined unit tests for the '/delete' route.", () => {
  it("'/app/delete' and '/delete' are registered routes in the app.  __exists __core", () => {
    const routes = ["/delete", "/app/delete"]
    const exists = routeExists(routes)
    expect(exists).toBe(true)
  })
})

describe('Check to see that critical repo files are present', () => {
  it('root folder files', () => {
    const filePath = './' // Replace with the actual file path
    expect(fs.existsSync(filePath+"CODEOWNERS")).toBeTruthy()
    expect(fs.existsSync(filePath+"CONTRIBUTING.md")).toBeTruthy()
    expect(fs.existsSync(filePath+"README.md")).toBeTruthy()
    expect(fs.existsSync(filePath+".gitignore")).toBeTruthy()
    expect(fs.existsSync(filePath+"jest.config.js")).toBeTruthy()
    expect(fs.existsSync(filePath+"package.json")).toBeTruthy()
  })
})
