name: TinyNode Dev Deploy on PR to main
on:
  pull_request:
    branches: CD-update-for-contributions
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge with main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: ${{ github.head_ref }}
          github_token: ${{ secrets.BRY_PAT }}
          message: Merge main into this branch to deploy to dev for testing.
  test:
    needs: merge-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run runtest
  deploy:
    if: github.event.pull_request.draft == false
    needs: [merge-branch, test]
    strategy:
      matrix:
        machines: [vlcdhp02]
    runs-on: ${{ matrix.machines }}
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "Development Deploy Occurred"
