name: TinyNode Dev Deploy on PR to main
on:
  pull_request:
    branches: CD-update-for-contributions
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge with main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: CD-update-for-contributions
          target_branch: ${{ github.head_ref }}
          github_token: ${{ secrets.BRY_PAT }}
          message: Merge main into this branch to deploy to dev for testing.
  test:
    needs: merge-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env from secrets
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          envkey_REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          envkey_RERUM_REGISTRATION_URL: ${{ secrets.RERUM_REGISTRATION_URL }}
          envkey_RERUM_API_ADDR: ${{ secrets.RERUM_API_ADDR }}
          envkey_RERUM_ID_PATTERN: ${{ secrets.RERUM_ID_PATTERN }}
          envkey_RERUM_ACCESS_TOKEN_URL: ${{ secrets.RERUM_ACCESS_TOKEN_URL }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      # Speed up subsequent runs with caching
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies then run test script
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run runtest
  deploy:
    if: github.event.pull_request.draft == false
    needs: [merge-branch, test]
    strategy:
      matrix:
        machines: [vlcdhp02]
    runs-on: ${{ matrix.machines }}
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "Development Deploy Occurred"
