name: TinyNode end to end tests on PR to deepfakemain
on:
  pull_request:
    branches: deepfakemain
jobs:
  test:
    strategy:
      matrix:
        machines:
          - vlcdhp02
    runs-on: ${{ matrix.machines }}
    steps:
      - uses: actions/checkout@master
      - name: Test the app on the server
        run: |
          cd /srv/node/tiny-node/
          git stash
          git checkout $GITHUB_HEAD_REF
          git pull
          npm install
          npm run E2Etests
          